### ISSUE TITLE
Populate recipes

### ISSUE THREAD

**Issue by rw4n99** [SchoolOfCode/bc17-w5d1-catch-up-express-api-with-file-storage-rmf#1]
First, using the table below as a guide, get your CRUD routes up and running in your router so that your server listens for requests and serves test/example responses for now.

Remember that you can test your routes with Postman or Thunder Client to ensure they're working.
```[tasklist]
### Tasks
- [ ] Import recipes.json to the app.js file
- [ ] get your CRUD routes up and running
- [ ] test the endpoint with postman
```

**Comment by rw4n99** [comment]
First, using the table below as a guide, get your CRUD routes up and running in your router so that your server listens for requests and serves test/example responses for now.

Remember that you can test your routes with Postman or Thunder Client to ensure they're working.
